version: '3.8'

services:
  # --- 1. BASE DE DATOS (MySQL) ---
  database:
    image: mysql:8.0
    container_name: animelist-db
    restart: always
    environment:
      # Credenciales para que coincidan con tu backend y phpmyadmin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime_list_db  # Coincide con el "USE" del init.sql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # IMPORTANTE: Aquí cargamos el archivo init.sql que creaste en la carpeta database
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # --- 2. GESTOR VISUAL (phpMyAdmin) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: animelist-pma
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80" # Entrarás en http://localhost:8081
    networks:
      - app-network

  # --- 3. BACKEND (Node.js) ---
  backend:
    build:
      context: ./backend # CAMBIO IMPORTANTE: Apunta a tu carpeta nueva
      dockerfile: Dockerfile
    container_name: animelist-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      # Variables para que tu código Node sepa conectarse a la BD
      DB_HOST: database 
      DB_USER: root
      DB_PASS: root
      DB_NAME: anime_list_db
      PORT: 3000
    networks:
      - app-network

  # --- 4. FRONTEND (React + Nginx) ---
  frontend:
    build:
      context: ./frontend # CAMBIO IMPORTANTE: Apunta a tu carpeta nueva
      dockerfile: Dockerfile
    container_name: animelist-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: # Volumen para guardar los datos de MySQL aunque apagues el PC